# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e045bcc2bce6be3b286d43e3edd02e1d8194a4b1fcfc25951743f80dc2d9ed5d3090783a7645beae5d37e62d941d210c29a13bb4026e233c72965124a14dfbc

test:
  secret_key_base: 1c579fff36d88cec8175fa18104fabf888d255073a74b42c312b5749e2aad744c7369567e0ab3c2b590e612097bb163527ac1ed2c60233e1871158c299de8daa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
